EnCiv/civil-pursuit

.gitignore, .storybook/webpack.config.js, webpack-dev.config.js
npm run storybook wasn't working
changed the function to looking for client-side-model
=> fix: change normal module replacement

.gitignore, app/components/app.jsx, app/server/server.js
=> feat: add redirect to env variable LANDING_PAGE_REDIRECT_PATH

.storybook/preview.js, package-lock.json, package.json, stories/item.stories.jsx, stories/old_item.js
#issue28. I converted item.stories.jsx to Storybook7. Storybook7 typically interacts with the component as a user would, so I Left some cases which directly interact with component's method unconverted in comments.
=> Storybook7 item.jsx

.storybook/main.js, .storybook/test-runner.ts, package-lock.json, package.json
Accessibility test are displayed next to interactions in storybook. To run test runner:
Start your Storybook. >>npm run storybook
open a new terminal window and run the test-runner with: >>npm run test-storybook
=> add accessibility test and test runner

app/components/status-badge.jsx, app/components/theme.js, stories/status-badge.stories.jsx
Let me know if there are any changes I can make, thanks!
=> Status badge component#47

post-install.sh
don't webpack and the rest if this is a dependency in a different NPM_PROJECT
=> NPM_PROJECT env

app/components/button.jsx, app/components/point-group.jsx, app/components/theme.js, stories/point-group.stories.jsx
=> finish of point group component

app/components/point.jsx, stories/point.stories.jsx
Resolves #76 
This is still in progress. Opening as a draft for feedback and to make sure this is going in the right direction.
=> Adding Point loading visual state #76

app/api/__tests__/upsert-why.js, app/api/upsert-why.js
For the point.js, I am using `title` as one of the required components instead of `subject`. You might need to make a clearfication on other docs that is using subject as one of the required components. The structure of upsert-why is really simmilar to upsert-point, could you explain why do we need two of these api? Am I doing it wrong?
=> Upsert why#133

app/api/__tests__/get-random-whys.js, app/api/get-random-whys.js
=> Get random whys#135

app/api/__tests__/insert-dturn-statement.js, app/api/insert-dturn-statement.js
This implements the API for inserting a new statement into the DB and adding the statement to the Dturn, along with jest tests for various success/failure scenarios.
=> Insert dturn#163

app/components/step-bar.jsx, app/components/step-footer.jsx, app/components/step-slider.jsx, app/components/step.jsx, stories/step-slider.stories.jsx
This change implements the StepSlider component. It also includes some fixes and modifications to StepBar.
=> Step slider#112

app/dturn/dturn.js, app/socket-apis/__tests__/post-point-groupings.js, app/socket-apis/post-point-groups.js, package-lock.json, package.json
This change implements the postPointGroups API, along with JEST tests to verify functionality.
=> Post pgroups#178

app/socket-apis/__tests__/rank-why.js, app/socket-apis/rank-why.js
rank-why function and the test for it. Test contains 4 parts including insert rankObj, update rankObj, fail if not logged in, fail if parameters missing
=> Creat rank-why function and test for rank-why#134

app/socket-apis/__tests__/get-points-for-round.js, app/socket-apis/get-points-for-round.js
This implements the API and test cases to retrieve point docs from a discussion round.
=> Get roundpts#204

app/dturn/dturn.js, app/models/__tests__/rankings.js, app/models/__tests__/ranks.js, app/models/rankings.js, app/models/ranks.js, app/socket-apis/__tests__/get-top-ranked-whys-for-point.js, app/socket-apis/__tests__/get-user-ranks.js, app/socket-apis/__tests__/rank-why.js, app/socket-apis/get-top-ranked-whys-for-point.js, app/socket-apis/get-user-ranks.js, app/socket-apis/rank-why.js
This implements the API to get rankings made by a user and adds fields to the Ranking model.
=> Get userranks#205

app/socket-apis/__tests__/get-user-whys.js, app/socket-apis/get-user-whys.js
getUserWhys API and jest test.(https://github.com/EnCiv/civil-pursuit/issues/206)
Test 1: User not logged in
Test 2: Return empty array if no data found
Test 3: Return list of 5 items
=> getUserWhys API 

.storybook/preview.js, app/components/deliberation-context.js, app/components/steps/rerank.js, stories/common.js, stories/rerank-step.stories.js
Added the code to call the socket apis from rerankstep, and updated the story to test it.
=> Rerank apis

app/components/question-box.jsx, stories/question-box.stories.jsx
https://github.com/EnCiv/civil-pursuit/issues/223
=>  Content alignment options for QuestionBox #223

app/models/points.js, app/socket-apis/__tests__/get-points-for-round.js, app/socket-apis/__tests__/get-points-of-ids.js, app/socket-apis/__tests__/get-random-whys.js, app/socket-apis/__tests__/get-top-ranked-whys-for-point.js, app/socket-apis/__tests__/get-user-whys.js, app/socket-apis/__tests__/insert-dturn-statement.js, app/socket-apis/__tests__/rank-why.js, app/socket-apis/__tests__/upsert-point.js, app/socket-apis/__tests__/upsert-rank.js, app/socket-apis/__tests__/upsert-why.js
the point model uses subject not title
using the Model rather than mongo.db.collections(
=> Point subject

app/components/round-tracker.js, app/components/theme.js, stories/round-tracker.stories.js
=> RoundTracker redesign #243

app/components/button.jsx, assets/svg/plus-sign.svg, stories/button.stories.jsx
changes have been done according to the backlog
=> Buttons#246

app/components/deliberation-context.js, app/components/footer.jsx, app/components/more-details.jsx, app/components/tournament.js, app/socket-apis/__tests__/get-user-post-ranks-and-top-ranked-whys.js, app/socket-apis/get-user-post-ranks-and-top-ranked-whys.js, app/web-components/civil-pursuit.js, iotas.json
uses jfform model and apis, other cleanup and fixes.
=> Get more details
